# Generated by Django 4.1.3 on 2022-11-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('sexo', models.CharField(max_length=1)),
                ('data_nasc', models.DateField()),
                ('cargo_pretendido', models.CharField(max_length=25)),
                ('texto_curriculo', models.TextField()),
            ],
        ),
    ]
